### ISSUE TITLE
Incompatibility with latest scss

### ISSUE THREAD

**Issue by AsafAgranat** [Noxu/material-layout#2]
This package is great, but unfortunately unusable. It is incompatible with the latest fourseven:scss (3.8.1), and running meteor with --allow-incompatible-update leads to errors.
I see that this package was not installed much, and haven;t been updated in 2 years, but it would be great if it could be updated to latest dependencies.
Thanks!

**Comment by Cram974** [comment]
Thank you for the feedback! We though no one was using it so we didn't maintained it. We will update the package soon.
